### ISSUE TITLE
Heading #3 and #4 are not rendered properly on "preparing-your-application"

### ISSUE THREAD

**Issue by abhiShandy** [capistrano/capistrano.github.io#121]
check this page:
http://capistranorb.com/documentation/getting-started/preparing-your-application/

**Comment by jtwarren** [comment]
Was taking a look at this locally and then it seemed to be resolved when I checked the docs again.  Looks good to me now.

**Comment by leehambley** [comment]
For me too, we had a couple of PRS recently

**Comment by abhiShandy** [comment]
Docs are fine, possibly some glitch in rendering the md files on the server
