### ISSUE TITLE
gitattributes page is not linked; code renders improperly

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano.github.io#150]
I noticed that the new documentation page about `.gitattributes` is not listed anywhere on the site. I believe it needs to be added to `_includes/navigation.html`.

Also, for some reason the code block is not rendering properly:

![screen shot 2016-01-17 at 8 24 59 am](https://cloud.githubusercontent.com/assets/189693/12378486/0b27fa44-bcf4-11e5-993c-944a375f3121.png)

@will-in-wi Would you mind pushing a fix?

**Comment by mattbrictson** [comment]
Direct link: http://capistranorb.com/documentation/advanced-features/ignoring/

**Comment by will-in-wi** [comment]
This is fixed now.
