### ISSUE TITLE
GitHub Pages emits warning about syntax highlighter

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano.github.io#168]
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

**Comment by leehambley** [comment]
Thanks @mattbrictson
