### ISSUE TITLE
GitHub Pages emits warning about Markdown engine

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano.github.io#172]
:weary: 

> You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

**Comment by leehambley** [comment]
Bah, it _should_ be fine thou Matt. I'll have a quick look.

**Comment by leehambley** [comment]
This issue was moved to capistrano/capistrano#1761
