### ISSUE TITLE
Move docs into capistrano repository?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano.github.io#174]
/cc @leehambley @will-in-wi @robd 

I'm not sure if this is a good idea, or even how it would be done, so I thought I should open it for discussion.

Basically I've noticed that it is hard to keep the documentation site up to date, and part of that is because it is a separate Git repository.

With Capistrano's CHANGELOG and README, we can easily set a policy that those must be updated when an Capistrano PR adds new features or makes changes. And indeed the CHANGELOG is one of the few bits of official documentation that is very well maintained.

However the site being a separate repository, we can't enforce policy via the normal PR process.

What if:
- The docs were moved into the capistrano repository under `docs/`
- Our PR policy could expand to ensure both CHANGELOG _and_ docs are updated on merge
- Somehow (???) we build the public doc site from `docs/`
- Bonus: the public doc site could have both "edge" and "stable" versions, built from `master` and the most recent tag

Anyway, I'm not sure this could work, but given that documentation is one of our biggest challenges, I thought it worthy of discussion.

Good idea? Bad idea?

**Comment by leehambley** [comment]
I prefer to keep them in separate repositories, previously it has been a Wiki at GitHub, a Jekyll site under a gh-pages branch or similar.

I think that they have different release cycles, and it's valuable to have different repos for different components.

Frankly I've not been too impressed with any of these things, and it's relatively seldom we get a request which warrants _really_ new documentation, but I couldn't vote definitely for keeping, or moving it. In lieu of a _definitive_ better option I'm inclined not to change anything.

**Comment by leehambley** [comment]
> Somehow (???) we build the public doc site from docs/

We could use www.harrow.io for that, I'm currently speccing out how we can do all releases (including signed Gems) via harrow, since resolving this "oopse, I can't push RubyGems!" was a motivation for building it!

**Comment by will-in-wi** [comment]
I'm inclined to encourage that they stay distinct. The reason for this is that I would rather not have to wait for a release to have new stable documentation updates. It might be worth establishing a convention for version specific documentation notes, such as a new documented feature which is only available after version x.y.z. But, if I want to write some new docs which apply to older versions, it is tough to do this when the repos are merged.

Per requiring docs, I'm not against having a PR requirement that new features also get documented. This might take the form of linking to a PR for the docs which would get committed when the feature itself gets committed, albeit with version notes as above.

My 2 cents. Thanks for your work on this!

**Comment by mattbrictson** [comment]
Good points all around. Let's keep it as a separate repo.

**Comment by leehambley** [comment]
The shortest, most amicable discussion ever raised on this issue tracker :beers:  for everyone!
