### ISSUE TITLE
harrow.io modal reappears even after "no thanks"

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano.github.io#178]
I believe it is because we're not specifying `path: "/"` when setting the cookie.

**Comment by leehambley** [comment]
I'll get someone on my team to check that Matt

(sent from my phone, please excuse typos)

**Comment by mattbrictson** [comment]
@leehambley I think I already have a fix ready in PR #179

**Comment by leehambley** [comment]
Yep, thanks merging. My emails are all out of order :-/

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667
