### ISSUE TITLE
Newbie feedback

### ISSUE THREAD

**Issue by rubydesign** [capistrano/capistrano.github.io#184]
Hi,

i just got it set up and it was a little difficult. I could help improve the docs, or say where there are unclarities if that is wanted. 
To be a little more specific: i found the setup and which commands are needed a little difficult. Especially in sight of the capistrano-rails, is it needed or not, what are the differences, difficult to follow.
Astep-by-step guide would be good too.

If someone is interested to work on this, i could help.

**Comment by leehambley** [comment]
This issue was moved to capistrano/capistrano#1760
