### ISSUE TITLE
[Continue Discussion] About Translation to Chinese

### ISSUE THREAD

**Issue by 1c7** [capistrano/capistrano.github.io#191]
https://github.com/capistrano/capistrano/issues/1690
here is continue discussion about topic in above link

I am busy on deploy a Rails app.
So when i got time i would come back and see what can we do to translate the website.
I don't know much about jekyll and github page.
maybe I can just fork & pull request or something to translate. I don't know.
anyway, when i got time i would come back.
:D

**Comment by chinakr** [comment]
Documentation is ver important. if needed, I'll do my bit. Thanks.

**Comment by leehambley** [comment]
This issue was moved to capistrano/capistrano#1759
