### ISSUE TITLE
Recommended use of `ask` is incorrect

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano.github.io#192]
The [documentation](http://capistranorb.com/documentation/getting-started/user-input/#) recommends this pattern:

``` ruby
set :database_password, ask('Enter the database password:', 'default', echo: false)
```

But this is wrong. The first argument to `ask` is supposed to be a variable name, not a prompt string. Technically the code still works (since the outer `set` overrides the implicit `set` within `ask`), but it is very misleading.

**Comment by leehambley** [comment]
This issue was moved to capistrano/capistrano#1758
