### ISSUE TITLE
Return the documentation history

### ISSUE THREAD

**Issue by BookOfGreg** [capistrano/capistrano.github.io#199]
Hi,

The documentation at https://github.com/capistrano/capistrano/tree/master/docs only contains V3.7
I'm looking for the documentation for V3.6 and this repo has had it's history deleted.

Please can this repositories history be returned for archival purposes?

Thank you,
Greg

Edit: For anyone arriving here from Google, [History exists on other people's forks](https://github.com/capistrano/documentation/network) (Hello to the future)

**Comment by leehambley** [comment]
I at least don't have a copy, and there were no significant changes between 3.6 and 3.7

**Comment by BookOfGreg** [comment]
https://github.com/capistrano/capistrano/blob/v3.6.1/UPGRADING-3.7.md

I assumed there was a change due to the above doc mentioning Capistrano::SCM::Git which does not exist in 3.6. If that is not the case then there is no smooth upgrade path between 3.6 and 3.7. Is that the case?

I'm currently attempting to write a new SCM strategy based on the custom git_strategy we've been running since v3.4 and experiencing a lot of trouble.

**Comment by leehambley** [comment]
> I'm currently attempting to write a new SCM strategy based on the custom git_strategy we've been running since v3.4 and experiencing a lot of trouble.

If you're targeting `< 3.7` nothing should have changed, if you're looking for `>=3.7` then the built-in SCMs are using the new plug-in architecture and serve as pretty easy-to-follow references.

If you're targeting `<3.7` you're probably punishing yourself quite badly, as 3.7 introduced the new plugin system to make pluggable SCMs easier, @mattbrictson was the primary stakeholder and author on our side, but they should be very simple to implement.

Outside of the SCM stuff, essentially nothing important changed between 3.6 and 3.7 which would warrant running an old version.

**Comment by BookOfGreg** [comment]
Thanks for the information. I'll stick with the current flow until we need to move to 3.7.

This issue was originally for the docs so I'll consider this closed if there isn't a convenient history available.
Thanks.

**Comment by will-in-wi** [comment]
I have an older copy in a fork here: https://github.com/will-in-wi/documentation

The changes in 3.7 are supposed to make your life easier in this exact case, so I'd encourage you to look at that.

**Comment by leehambley** [comment]
> The changes in 3.7 are supposed to make your life easier in this exact case, so I'd encourage you to look at that.

Definitely, I can't state strongly enough how much you ought to upgrade to 3.7 - it includes nothing that you should be afraid of. We work incredibly hard to make sure there's virtually no reason not to be running the latest version of Capsitrano.

**Comment by mattbrictson** [comment]
> I'm looking for the documentation for V3.6 and this repo has had it's history deleted

We retained all history of the documentation.

```
git log 9d62e3d
```

👆 That will show you every commit ever made to the documentation.

Historically, we never tagged documentation for specific Capistrano releases. Therefore your best bet of seeing the documentation as of v3.6 is to use a date qualifier when viewing the history. Capistrano 3.6 was released on July 26, so you could run:

```
git log 9d62e3d --until 2016-07-26
```

Which reveals d7c2a11 as the latest documentation commit prior to the 3.6 release.

**Comment by mattbrictson** [comment]
I should also mention that the entire history of the documentation was imported into the [main capistrano repository](https://github.com/capistrano/capistrano), so the `git` usage I demonstrated can and should be done there instead. Here is that same commit which was imported into the capistrano repo:

https://github.com/capistrano/capistrano/commit/d7c2a11d3b3137601a4447c80a3c172ef7dc042d
