### ISSUE TITLE
404 issues with new site. capistranorb.com

### ISSUE THREAD

**Issue by seenmyfate** [capistrano/capistrano.github.io#22]
See [discussion on Capistrano issue #561](https://github.com/capistrano/capistrano/issues/561)

**Comment by Kriechi** [comment]
I did a brief check of the links - didn't find anything broken.
Can be closed I guess.

**Comment by leehambley** [comment]
I don't know what this was about either, since the links are autogenerated from Jekyll. I think it might have been to do with the Github Pages infrastructure changes that happened a while ago, and they started linking to a "brown out" page for people who hadn't updated their DNS
