### ISSUE TITLE
markdown syntax exposed

### ISSUE THREAD

**Issue by mauriciopasquier** [capistrano/capistrano.github.io#77]
For example [here](http://capistranorb.com/documentation/getting-started/installation/). But I don't know how to fix this, the [file seems ok](https://github.com/capistrano/capistrano.github.io/blob/master/documentation/getting-started/installation/index.markdown) (and github converts it differently). Maybe those `highlight` tags are to blame.

**Comment by Kriechi** [comment]
I can't see anything - maybe it is already fixed?
If already fixed - please close this issue,
or provide a screenshot to indicate the problem.

Thanks.

**Comment by mauriciopasquier** [comment]
I should have linked to the specific version of the file. It seems to have been fixed [here](https://github.com/capistrano/capistrano.github.io/commit/894b9758aa69db88df135d00aa9d71de9746dac4), thanks
